### ISSUE TITLE
Train to remember faces?

### ISSUE THREAD

**Issue by abrad1212** [xionghc/Facial-Expression-Recognition#1]
Is it possible to train it to recognize people's faces? Im sure it's possible it's the matter of implementation, and with your smart brain I'm sure you know how to implement it :)

**Comment by xionghc** [comment]
I recognize the faces  in picture before emotion recognition. Due to some problems, the box of faces is hided. Now the code have been updated,  a '--showbox' parameter can make box display  in the window. Thank you.
