### ISSUE TITLE
About WIN10

### ISSUE THREAD

**Issue by infinitr0us** [xionghc/Facial-Expression-Recognition#12]
My laptop runs WIN10 of Ver1803 and I got no answer running"python3 main.py demo". I have already downloaded the demo files and put models folder in it. Should I open camera application first and then run the Python files? Thank you very much.

**Comment by youshenjun** [comment]
Should open webcamera application firt and then run? thank you

**Comment by xionghc** [comment]
Same as Issues #13 .
