### ISSUE TITLE
No emojis face 

### ISSUE THREAD

**Issue by aNothing** [xionghc/Facial-Expression-Recognition#13]
When I use following command to do expression recognition, there is no emojis face.
**python3 main.py demo valid** 

system information:
Ubuntu 16.04
Tensorflow 1.7
Opencv 3.4.0
Python 3.5

**Comment by xionghc** [comment]
Remove ``valid'' argument. Using **python3 main.py demo**.

**Comment by aNothing** [comment]
It gives out this error, when I use your commmand.

usage: main.py [-h] [--modelPath MODELPATH] [--showbox] func train_or_valid
main.py: error: the following arguments are required: train_or_valid

**Comment by xionghc** [comment]
Sorry. Please try **python3 demo.py** and make sure the model file in a current folder.

**Comment by aNothing** [comment]
![image](https://user-images.githubusercontent.com/18108332/41021299-81f3b886-6998-11e8-8838-f05cd591e5fb.png)

By using **python3 demo.py**, the camera can work there are no emojis on the screen.

**Comment by xionghc** [comment]
Using SPACE button to capture your current face.

**Comment by snowalala** [comment]
Sorry. I have the same problem as you. I used **python3 demo.py** , and used SPACE, but I can't see emojis on the screen. I want to know why, thanks.

**Comment by aNothing** [comment]
I tested **python3 demo.py**, this time I also did not see the emojis. I am so curious about this result, maybe we need the author's help.

**Comment by xionghc** [comment]
I modified the code of program, it is easier  to use than before. To run demo, just type:
```shell
python3 main.py
```

Please fetch the latest commit to try that. Thank you for your support.
