### ISSUE TITLE
There is nothing when I press the apacekey.

### ISSUE THREAD

**Issue by spkll** [xionghc/Facial-Expression-Recognition#18]
After the python3 main.py ,there is the NOTE:Press SPACE on keyboard to capture face.And I pressed the spacekey, it is no answer .For quite a while, the terminal shows the print that traceback (most recetn call last):..............
AttributeErrot:'NoneType' object has no attribute ''shape

**Comment by xionghc** [comment]
Did you use the latest code? This problem have been fixed in the recent commit.

**Comment by spkll** [comment]
Yes ,I downloaded tow days ago.




------------------ 原始邮件 ------------------
发件人: "Xionghc"<notifications@github.com>;
发送时间: 2018年10月10日(星期三) 下午3:00
收件人: "xionghc/Facial-Expression-Recognition"<Facial-Expression-Recognition@noreply.github.com>;
抄送: "defeatmyself"<982905429@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [xionghc/Facial-Expression-Recognition] There is nothing when Ipress the apacekey. (#18)




Did you use the latest code? This problem have been fixed in the recent commit.

**Comment by xionghc** [comment]
Can you locate which variable throw this error?

**Comment by spkll** [comment]
Maybe I know the reason .There is someting wrong with my camera drive in ubuntu.I am solving the problem.After that I will give you the answer. 




------------------ 原始邮件 ------------------
发件人: "Xionghc"<notifications@github.com>;
发送时间: 2018年10月10日(星期三) 下午3:21
收件人: "xionghc/Facial-Expression-Recognition"<Facial-Expression-Recognition@noreply.github.com>;
抄送: "defeatmyself"<982905429@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [xionghc/Facial-Expression-Recognition] There is nothing when Ipress the apacekey. (#18)




Can you locate which variable throw this error?
