### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by Zumbalamambo** [xionghc/Facial-Expression-Recognition#2]
can you please share the pretrained model?

**Comment by xionghc** [comment]
Yes. The pretrained model has been released, you can find the download link in README.

**Comment by yuzhenbo** [comment]
the demo can not recognize the expression, it just show my video

**Comment by xionghc** [comment]
@yuzhenbo Using 'python3 mean.py demo' command.

**Comment by xionghc** [comment]
@yuzhenbo Using 'python3 main.py demo' command.

**Comment by xionghc** [comment]
@yuzhenbo I'm sorry. Because the computer may can't process realtime, so I set 'SPACE' button to capture face.
