### ISSUE TITLE
你好，我用你的程序跑了一会出现了下面的错误，麻烦你能给我一些指导吗？

### ISSUE THREAD

**Issue by lenghanyan** [xionghc/Facial-Expression-Recognition#3]
****
![image](https://user-images.githubusercontent.com/33375947/32406851-aeea1686-c1ba-11e7-9524-bfc863cb3c0a.png)

**Comment by xionghc** [comment]
@lenghanyan Do you pass a "demo" or " "train" argument to program?

**Comment by lenghanyan** [comment]
No, I just downloaded the program you uploaded and then ran it with spyder, and then it went wrong

**Comment by lenghanyan** [comment]
Do you need to use your data?

**Comment by lenghanyan** [comment]
Do i need to use your data?

**Comment by lenghanyan** [comment]
May I have your contact information, please?

**Comment by xionghc** [comment]
Please read "**README**" carefully.  Firstly, you need download the model file, Secondly, run program using command 

> python3 man.py demo

**Comment by xionghc** [comment]
@lenghanyan If problem still exist, Wechat me.

**Comment by lenghanyan** [comment]
alright, thank you very much！

**Comment by lenghanyan** [comment]
Is it still online?Can I add your WeChat?

**Comment by xionghc** [comment]
@lenghanyan xhc654321
