### ISSUE TITLE
how to save  like the jpg of AmazingKelly,w

### ISSUE THREAD

**Issue by liuhuihuii** [xionghc/Facial-Expression-Recognition#31]
When I run the demo, It just save the a.jpg about 48 * 48,only size 2 KB

**Comment by liuhuihuii** [comment]
Urgent!!Can you tell me how to save the pic like AmazingKelly automatically,thank you very much.

**Comment by xionghc** [comment]
Add `cv2.imsave('amazing.jpg', frame)` in `demo.py` before line 121.

**Comment by zhanghongruiupup** [comment]
你好，运行main.py，能打开摄像头，但是没有识别出表情。谢谢

**Comment by xionghc** [comment]
@zhanghongruiupup Pressing `SPACE` button to capture emotion.
