### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by kmoonctx** [xionghc/Facial-Expression-Recognition#37]
您好，我是上海交大的一名学生，最近在跑您的代码，运行main函数的时候不知道为什么出现了这样的bug，能麻烦您指点一下吗。
Restore model sucsses!!
NOTE: Press SPACE on keyboard to capture face.
 OpenCV Error: Unspecified error (The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script) in cvWaitKey, file /opt/conda/conda-bld/opencv_1491943704081/work/opencv-3.1.0/modules/highgui/src/window.cpp, line 616
Traceback (most recent call last):
  File "main.py", line 29, in <module>
    main()
  File "main.py", line 22, in main
    demo(FLAGS.checkpoint_dir, FLAGS.show_box)
  File "/home/lgy/chutingxuan/Facial-Expression-Recognition-master/demo.py", line 105, in demo
    if cv2.waitKey(1) & 0xFF == ord(' '):
cv2.error: /opt/conda/conda-bld/opencv_1491943704081/work/opencv-3.1.0/modules/highgui/src/window.cpp:616: error: (-2) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function cvWaitKey

**Comment by kmoonctx** [comment]
哦不用了 我已经解决了 谢谢！

**Comment by xionghc** [comment]
ok！
