### ISSUE TITLE
Can't show expression? 

### ISSUE THREAD

**Issue by 812406210** [xionghc/Facial-Expression-Recognition#6]
I use your models to running this programmming ,only to show my image,Can't show expression?

**Comment by hmwc123** [comment]
when you running this programmming, and see your image. 
Press the "space" bar~~~

**Comment by 812406210** [comment]
thanks , I have no problem!

**Comment by Lydia0402** [comment]
@812406210  Hi I encountered the same problem like #5. How did you solve it?

**Comment by xionghc** [comment]
@Lydia0402 How did you solve the problem #5 , many people encounter this problem , but I don't know what is the reason.
